spring.application.name=broasterbackend
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:AVNS_hPRVeX3z56brYnXut15}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-b5fc52-jerson-6b26.c.aivencloud.com:28473/defaultdb?useSSL=true&requireSSL=true&verifyServerCertificate=false}
spring.jpa.hibernate.ddl-auto=none
server.port=${PORT:8080}

# CONFIGURACION DE INICIALIZACION SQL
spring.sql.init.mode=${SQL_INIT_MODE:always}
spring.sql.init.schema-locations=classpath:db-init.sql
# Le dice a Hibernate que use los nombres de columna y tabla tal como estan escritos en las anotaciones
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



# CONFIGURACION SMTP DE GMAIL

spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:adm1ndelifastfood@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:aroq jvmc hnrr hpxi}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000



# CONFIGURACION DE NUBEFACT API

nubefact.api.url=${NUBEFACT_API_URL:https://api.nubefact.com/api/v1/}

nubefact.api.ruc=${NUBEFACT_API_RUC:fb4303f4-c526-4d21-94ff-60f1cade1363}

nubefact.api.token.header=${NUBEFACT_API_TOKEN:83a83140d34c447ba7d12d0e5c0fd9e4bbd4a5aefe5846eeb191b04486c28ee3}

# === CONFIGURACION NIUBIZ SANDBOX/TEST ===
# URL para obtener el Token de Seguridad
niubiz.url.security=${NIUBIZ_URL_SECURITY:https://apitestenv.vnforapps.com/api.security/v1/security}
# URL para crear la sesion de compra (formulario)
niubiz.url.session=${NIUBIZ_URL_SESSION:https://apisandbox.vnforappstest.com/api.ecommerce/v2/ecommerce/token/session/}
# Credenciales Publicas
niubiz.merchant.id=${NIUBIZ_MERCHANT_ID:456879852}
niubiz.user=${NIUBIZ_USER:integraciones@niubiz.com.pe}
niubiz.password=${NIUBIZ_PASSWORD:_7z3@8fF}


# CONFIGURACION IA GROQ
gemini.api.url=${GEMINI_API_URL:https://api.groq.com/openai/v1/chat/completions}
gemini.api.key=${GEMINI_API_KEY}

# DECOLECTA API PARA DNI Y RUC
decolecta.api.key = ${DECOLECTA_API_KEY:sk_12143.sQvmEF1tvOWp5rFs5TQRdoYGPino9DZD}
decolecta.reniec.url = ${DECOLECTA_RENIEC_URL:https://api.decolecta.com/v1/reniec/dni?numero=}
decolecta.sunat.ruc.url = ${DECOLECTA_SUNAT_RUC_URL:https://api.decolecta.com/v1/sunat/ruc?numero=}