name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'broasteriabackend-main/**'
      - 'broasteriafrontend-main/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy files to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.AZURE_USER }}/broasteria"
          overwrite: true

      - name: Execute deployment commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/broasteria/broasteriabackend-main
            # Aseguramos que el archivo .env exista para que no falle Docker
            touch .env
            # Reconstruimos las imagenes (frontend y backend) y levantamos los contenedores
            sudo docker compose up -d --build
